# -*- coding: utf-8 -*-
"""Copy of Python for Github

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPSAiWpLesgvziiSA_5y73Dchecdt8R8
"""

print("hello")

"""What this does is running the "print()" function, it tells the computer to display what is in the brackets."""

name="Faith"
print(name)

"""Initially we have created a variable 'name' and given it a value 'Faith', thereafter used the "print()" function to print the variable. This whole process is how to store and retrive data."""

pens=15
pencils=3
total_stationery=pens+pencils
print(total_stationery)
differnce=pens-pencils
print(differnce)
product=pens*pencils
print(product)
quotient=pens/pencils
print(quotient)



user_name = input("Enter your name: ")
birth_year = input("Enter the year you were born: ")

birth_year_integer = int(birth_year)
current_age = 2026 - birth_year_integer

print("--- YOUR STORY ---")
print("Hello " + user_name + "!")
print("Because you were born in " + birth_year + ", you turn " + str(current_age) + " this year!")