# -*- coding: utf-8 -*-
"""Loops (for)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBbeFYa_eK0_mPi55-qH_CyazDLPN-h_
"""

# 1. A simple loop that counts down
print("Preparing for launch...")

for number in range(10, 0, -1):
    print(number)

print("Blast off! ")

print("Looking for even numbers...")

for i in range(1, 11):
    if i % 2 == 0:
        print(str(i) + " is even!")